// GENERATED by tools/build-components.mjs from mcp/examples/*.steps.json — do not edit.
import type { ComponentTemplate } from './components.ts';

export const COMPONENT_TEMPLATES: readonly ComponentTemplate[] = [
 {
  "id": "spark-burst",
  "label": "Spark burst",
  "description": "Velocity-stretched sparks with glowing trails, three bursts.",
  "durationTicks": 0,
  "anchors": [],
  "nodes": [
   {
    "id": "sched",
    "type": "Schedule",
    "params": {
     "startTicks": 0,
     "durationTicks": 1,
     "mode": "repeat",
     "repeatCount": 3,
     "repeatIntervalTicks": 30
    }
   },
   {
    "id": "em",
    "type": "Emitter",
    "params": {
     "shape": "cone",
     "direction": [
      0,
      1,
      0
     ],
     "coneAngle": 1.1,
     "radius": 0.05,
     "burst": 90,
     "rate": 0,
     "speedMin": 3,
     "speedMax": 8,
     "lifetimeMin": 0.5,
     "lifetimeMax": 1.1
    }
   },
   {
    "id": "ip",
    "type": "InitialProperties",
    "params": {
     "sizeMin": 0.025,
     "sizeMax": 0.045,
     "rotationMin": 0,
     "rotationMax": 0,
     "angularVelocityMin": 0,
     "angularVelocityMax": 0
    }
   },
   {
    "id": "grav",
    "type": "Gravity"
   },
   {
    "id": "drag",
    "type": "Drag",
    "params": {
     "coefficient": 0.9
    }
   },
   {
    "id": "mat",
    "type": "Material",
    "params": {
     "blend": "additive",
     "emission": 1
    }
   },
   {
    "id": "bb",
    "type": "BillboardRenderer",
    "params": {
     "alignment": "velocity",
     "stretchRatio": 7,
     "pivot": 0.85,
     "colorOverLife": {
      "stops": [
       {
        "position": 0,
        "color": {
         "srgb": "#FFFFFF",
         "alpha": 1
        }
       },
       {
        "position": 0.3,
        "color": {
         "srgb": "#FFC060",
         "alpha": 1
        }
       },
       {
        "position": 0.7,
        "color": {
         "srgb": "#FF4010",
         "alpha": 0.8
        }
       },
       {
        "position": 1,
        "color": {
         "srgb": "#801000",
         "alpha": 0
        }
       }
      ]
     }
    }
   },
   {
    "id": "trailmat",
    "type": "Material",
    "params": {
     "blend": "additive",
     "tint": {
      "srgb": "#FF9A40",
      "alpha": 1
     },
     "opacity": 0.8
    }
   },
   {
    "id": "trail",
    "type": "ParticleTrail",
    "params": {
     "history": 0.25,
     "width": 0.018,
     "endFade": 0.4
    }
   }
  ],
  "edges": [
   [
    "node-source.out",
    "em.anchor"
   ],
   [
    "sched.start",
    "em.trigger"
   ],
   [
    "em.particles",
    "ip.particles"
   ],
   [
    "ip.particles",
    "grav.particles"
   ],
   [
    "grav.particles",
    "drag.particles"
   ],
   [
    "drag.particles",
    "bb.particles"
   ],
   [
    "mat.material",
    "bb.material"
   ],
   [
    "bb.visual",
    "node-output.visual"
   ],
   [
    "drag.particles",
    "trail.particles"
   ],
   [
    "trailmat.material",
    "trail.material"
   ],
   [
    "trail.visual",
    "node-output.visual"
   ]
  ],
  "knobs": [
   {
    "id": "count",
    "label": "Sparks per burst",
    "value": 90,
    "bindings": [
     {
      "node": "em",
      "parameter": "burst"
     }
    ]
   },
   {
    "id": "speed",
    "label": "Speed",
    "value": 8,
    "bindings": [
     {
      "node": "em",
      "parameter": "speedMax"
     },
     {
      "node": "em",
      "parameter": "speedMin",
      "scale": 0.375
     }
    ]
   },
   {
    "id": "size",
    "label": "Spark size",
    "value": 0.045,
    "bindings": [
     {
      "node": "ip",
      "parameter": "sizeMax"
     },
     {
      "node": "ip",
      "parameter": "sizeMin",
      "scale": 0.55
     }
    ]
   },
   {
    "id": "trail",
    "label": "Trail length",
    "value": 0.25,
    "bindings": [
     {
      "node": "trail",
      "parameter": "history"
     }
    ]
   },
   {
    "id": "gravity-drag",
    "label": "Air drag",
    "value": 0.9,
    "bindings": [
     {
      "node": "drag",
      "parameter": "coefficient"
     }
    ]
   }
  ]
 },
 {
  "id": "flame-jet",
  "label": "Flame jet",
  "description": "Textured flame flipbooks aimed Source→Target with turbulence, core glow and a flickering floor light.",
  "durationTicks": 180,
  "anchors": [
   {
    "id": "flamecenter",
    "position": [
     0,
     0.9,
     0
    ]
   }
  ],
  "nodes": [
   {
    "id": "sched",
    "type": "Schedule",
    "params": {
     "startTicks": 10,
     "durationTicks": 120,
     "mode": "window"
    }
   },
   {
    "id": "em",
    "type": "Emitter",
    "params": {
     "shape": "cone",
     "coneAngle": 0.1,
     "radius": 0.04,
     "rate": 600,
     "burst": 0,
     "speedMin": 7,
     "speedMax": 9,
     "lifetimeMin": 0.4,
     "lifetimeMax": 0.7,
     "rateOverWindow": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 0.15
       },
       {
        "x": 0.1,
        "y": 1
       },
       {
        "x": 0.8,
        "y": 1
       },
       {
        "x": 1,
        "y": 0
       }
      ]
     }
    }
   },
   {
    "id": "ip",
    "type": "InitialProperties",
    "params": {
     "sizeMin": 0.1,
     "sizeMax": 0.16,
     "rotationMin": 0,
     "rotationMax": 0,
     "angularVelocityMin": 0,
     "angularVelocityMax": 0,
     "randomFrameStart": false
    }
   },
   {
    "id": "lift",
    "type": "Gravity",
    "params": {
     "acceleration": [
      0,
      2.5,
      0
     ]
    }
   },
   {
    "id": "turb",
    "type": "NoiseForce",
    "params": {
     "mode": "curl",
     "amplitude": 5,
     "frequency": 0.9,
     "evolution": 1.2
    }
   },
   {
    "id": "drag",
    "type": "Drag",
    "params": {
     "coefficient": 0.5
    }
   },
   {
    "id": "mat",
    "type": "Material",
    "params": {
     "template": "SpriteTextured",
     "sprite": "flame-tongue-a",
     "blend": "normal",
     "opacity": 0.75
    }
   },
   {
    "id": "bb",
    "type": "BillboardRenderer",
    "params": {
     "alignment": "velocity",
     "stretchRatio": 2.4,
     "pivot": 0.25,
     "flipbookMode": "overLife",
     "sizeOverLife": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 0.6
       },
       {
        "x": 0.5,
        "y": 2.2
       },
       {
        "x": 1,
        "y": 2.6
       }
      ]
     },
     "opacityOverLife": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 0
       },
       {
        "x": 0.06,
        "y": 1
       },
       {
        "x": 0.55,
        "y": 0.8
       },
       {
        "x": 1,
        "y": 0
       }
      ]
     },
     "colorOverLife": {
      "stops": [
       {
        "position": 0,
        "color": {
         "srgb": "#FFFFFF",
         "alpha": 1
        }
       },
       {
        "position": 0.5,
        "color": {
         "srgb": "#FFE4C0",
         "alpha": 1
        }
       },
       {
        "position": 1,
        "color": {
         "srgb": "#E07040",
         "alpha": 0.6
        }
       }
      ]
     }
    }
   },
   {
    "id": "coremat",
    "type": "Material",
    "params": {
     "template": "SpriteTextured",
     "sprite": "flame-tongue-b",
     "blend": "additive",
     "opacity": 0.5
    }
   },
   {
    "id": "core",
    "type": "BillboardRenderer",
    "params": {
     "alignment": "velocity",
     "stretchRatio": 2.6,
     "pivot": 0.3,
     "flipbookMode": "overLife",
     "sizeOverLife": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 0.4
       },
       {
        "x": 1,
        "y": 0.9
       }
      ]
     },
     "opacityOverLife": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 1
       },
       {
        "x": 0.5,
        "y": 0.4
       },
       {
        "x": 1,
        "y": 0
       }
      ]
     }
    }
   },
   {
    "id": "lightwin",
    "type": "Schedule",
    "params": {
     "startTicks": 10,
     "durationTicks": 140,
     "mode": "window"
    }
   },
   {
    "id": "glow",
    "type": "PointLight",
    "params": {
     "color": {
      "srgb": "#FF8A3A",
      "alpha": 1
     },
     "intensity": 40,
     "range": 6,
     "flicker": 0.35,
     "flickerRate": 10,
     "intensityOverWindow": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 0
       },
       {
        "x": 0.05,
        "y": 1
       },
       {
        "x": 0.85,
        "y": 1
       },
       {
        "x": 1,
        "y": 0
       }
      ]
     }
    }
   },
   {
    "id": "centeranchor",
    "type": "Anchor",
    "params": {
     "anchorId": "flamecenter"
    }
   }
  ],
  "edges": [
   [
    "node-source.out",
    "em.anchor"
   ],
   [
    "node-target.out",
    "em.aim"
   ],
   [
    "sched.window",
    "em.window"
   ],
   [
    "em.particles",
    "ip.particles"
   ],
   [
    "ip.particles",
    "lift.particles"
   ],
   [
    "lift.particles",
    "turb.particles"
   ],
   [
    "turb.particles",
    "drag.particles"
   ],
   [
    "drag.particles",
    "bb.particles"
   ],
   [
    "drag.particles",
    "core.particles"
   ],
   [
    "mat.material",
    "bb.material"
   ],
   [
    "coremat.material",
    "core.material"
   ],
   [
    "bb.visual",
    "node-output.visual"
   ],
   [
    "core.visual",
    "node-output.visual"
   ],
   [
    "centeranchor.out",
    "glow.anchor"
   ],
   [
    "lightwin.window",
    "glow.window"
   ],
   [
    "glow.visual",
    "node-output.visual"
   ]
  ],
  "knobs": [
   {
    "id": "density",
    "label": "Density",
    "value": 600,
    "bindings": [
     {
      "node": "em",
      "parameter": "rate"
     }
    ]
   },
   {
    "id": "reach",
    "label": "Reach (speed)",
    "value": 9,
    "bindings": [
     {
      "node": "em",
      "parameter": "speedMax"
     },
     {
      "node": "em",
      "parameter": "speedMin",
      "scale": 0.78
     }
    ]
   },
   {
    "id": "spread",
    "label": "Spread",
    "value": 0.1,
    "bindings": [
     {
      "node": "em",
      "parameter": "coneAngle"
     }
    ]
   },
   {
    "id": "turbulence",
    "label": "Turbulence",
    "value": 5,
    "bindings": [
     {
      "node": "turb",
      "parameter": "amplitude"
     }
    ]
   },
   {
    "id": "size",
    "label": "Flame size",
    "value": 0.16,
    "bindings": [
     {
      "node": "ip",
      "parameter": "sizeMax"
     },
     {
      "node": "ip",
      "parameter": "sizeMin",
      "scale": 0.625
     }
    ]
   },
   {
    "id": "light",
    "label": "Floor light",
    "value": 40,
    "bindings": [
     {
      "node": "glow",
      "parameter": "intensity"
     }
    ]
   }
  ]
 },
 {
  "id": "smoke-plume",
  "label": "Smoke plume",
  "description": "Rising curl-noise smoke with growth and fade over life.",
  "durationTicks": 300,
  "anchors": [],
  "nodes": [
   {
    "id": "sched",
    "type": "Schedule",
    "params": {
     "startTicks": 0,
     "durationTicks": 240,
     "mode": "window"
    }
   },
   {
    "id": "em",
    "type": "Emitter",
    "params": {
     "shape": "disc",
     "direction": [
      0,
      1,
      0
     ],
     "radius": 0.25,
     "rate": 70,
     "burst": 0,
     "speedMin": 0.1,
     "speedMax": 0.3,
     "lifetimeMin": 2.5,
     "lifetimeMax": 3.5
    }
   },
   {
    "id": "ip",
    "type": "InitialProperties",
    "params": {
     "sizeMin": 0.25,
     "sizeMax": 0.4,
     "rotationMin": 0,
     "rotationMax": 0,
     "angularVelocityMin": 0,
     "angularVelocityMax": 0
    }
   },
   {
    "id": "lift",
    "type": "Gravity",
    "params": {
     "acceleration": [
      0.15,
      0.9,
      0
     ]
    }
   },
   {
    "id": "swirl",
    "type": "NoiseForce",
    "params": {
     "mode": "curl",
     "amplitude": 2.2,
     "frequency": 0.7,
     "evolution": 0.4
    }
   },
   {
    "id": "drag",
    "type": "Drag",
    "params": {
     "coefficient": 1.2
    }
   },
   {
    "id": "mat",
    "type": "Material",
    "params": {
     "blend": "normal",
     "opacity": 0.35
    }
   },
   {
    "id": "bb",
    "type": "BillboardRenderer",
    "params": {
     "sizeOverLife": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 0.5
       },
       {
        "x": 1,
        "y": 3
       }
      ]
     },
     "opacityOverLife": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 0
       },
       {
        "x": 0.15,
        "y": 1
       },
       {
        "x": 1,
        "y": 0
       }
      ]
     },
     "colorOverLife": {
      "stops": [
       {
        "position": 0,
        "color": {
         "srgb": "#8A8A8A",
         "alpha": 1
        }
       },
       {
        "position": 1,
        "color": {
         "srgb": "#3A3A40",
         "alpha": 1
        }
       }
      ]
     }
    }
   }
  ],
  "edges": [
   [
    "node-source.out",
    "em.anchor"
   ],
   [
    "sched.window",
    "em.window"
   ],
   [
    "em.particles",
    "ip.particles"
   ],
   [
    "ip.particles",
    "lift.particles"
   ],
   [
    "lift.particles",
    "swirl.particles"
   ],
   [
    "swirl.particles",
    "drag.particles"
   ],
   [
    "drag.particles",
    "bb.particles"
   ],
   [
    "mat.material",
    "bb.material"
   ],
   [
    "bb.visual",
    "node-output.visual"
   ]
  ],
  "knobs": [
   {
    "id": "amount",
    "label": "Amount",
    "value": 70,
    "bindings": [
     {
      "node": "em",
      "parameter": "rate"
     }
    ]
   },
   {
    "id": "swirl",
    "label": "Swirl",
    "value": 2.2,
    "bindings": [
     {
      "node": "swirl",
      "parameter": "amplitude"
     }
    ]
   },
   {
    "id": "size",
    "label": "Puff size",
    "value": 0.4,
    "bindings": [
     {
      "node": "ip",
      "parameter": "sizeMax"
     },
     {
      "node": "ip",
      "parameter": "sizeMin",
      "scale": 0.625
     }
    ]
   },
   {
    "id": "opacity",
    "label": "Opacity",
    "value": 0.35,
    "bindings": [
     {
      "node": "mat",
      "parameter": "opacity"
     }
    ]
   },
   {
    "id": "drag",
    "label": "Air drag",
    "value": 1.2,
    "bindings": [
     {
      "node": "drag",
      "parameter": "coefficient"
     }
    ]
   }
  ]
 },
 {
  "id": "fountain",
  "label": "Water fountain",
  "description": "Upward cone of droplets with gravity and bouncing ground collision.",
  "durationTicks": 240,
  "anchors": [],
  "nodes": [
   {
    "id": "sched",
    "type": "Schedule",
    "params": {
     "startTicks": 0,
     "durationTicks": 180,
     "mode": "window"
    }
   },
   {
    "id": "em",
    "type": "Emitter",
    "params": {
     "shape": "cone",
     "direction": [
      0,
      1,
      0
     ],
     "coneAngle": 0.22,
     "radius": 0.04,
     "rate": 260,
     "burst": 0,
     "speedMin": 5,
     "speedMax": 6.5,
     "lifetimeMin": 1.6,
     "lifetimeMax": 2.2
    }
   },
   {
    "id": "ip",
    "type": "InitialProperties",
    "params": {
     "sizeMin": 0.03,
     "sizeMax": 0.055,
     "rotationMin": 0,
     "rotationMax": 0,
     "angularVelocityMin": 0,
     "angularVelocityMax": 0
    }
   },
   {
    "id": "grav",
    "type": "Gravity"
   },
   {
    "id": "drag",
    "type": "Drag",
    "params": {
     "coefficient": 0.25
    }
   },
   {
    "id": "ground",
    "type": "GroundCollision",
    "params": {
     "mode": "bounce",
     "restitution": 0.35,
     "friction": 0.4,
     "maxBounces": 2
    }
   },
   {
    "id": "mat",
    "type": "Material",
    "params": {
     "blend": "additive"
    }
   },
   {
    "id": "bb",
    "type": "BillboardRenderer",
    "params": {
     "alignment": "velocity",
     "stretchRatio": 2.5,
     "pivot": 0.6,
     "colorOverLife": {
      "stops": [
       {
        "position": 0,
        "color": {
         "srgb": "#E8FAFF",
         "alpha": 1
        }
       },
       {
        "position": 0.6,
        "color": {
         "srgb": "#7CC8EA",
         "alpha": 0.8
        }
       },
       {
        "position": 1,
        "color": {
         "srgb": "#2A6A90",
         "alpha": 0
        }
       }
      ]
     }
    }
   }
  ],
  "edges": [
   [
    "node-source.out",
    "em.anchor"
   ],
   [
    "sched.window",
    "em.window"
   ],
   [
    "em.particles",
    "ip.particles"
   ],
   [
    "ip.particles",
    "grav.particles"
   ],
   [
    "grav.particles",
    "drag.particles"
   ],
   [
    "drag.particles",
    "ground.particles"
   ],
   [
    "ground.particles",
    "bb.particles"
   ],
   [
    "mat.material",
    "bb.material"
   ],
   [
    "bb.visual",
    "node-output.visual"
   ]
  ],
  "knobs": [
   {
    "id": "flow",
    "label": "Flow",
    "value": 260,
    "bindings": [
     {
      "node": "em",
      "parameter": "rate"
     }
    ]
   },
   {
    "id": "height",
    "label": "Jet speed",
    "value": 6.5,
    "bindings": [
     {
      "node": "em",
      "parameter": "speedMax"
     },
     {
      "node": "em",
      "parameter": "speedMin",
      "scale": 0.77
     }
    ]
   },
   {
    "id": "spread",
    "label": "Spread",
    "value": 0.22,
    "bindings": [
     {
      "node": "em",
      "parameter": "coneAngle"
     }
    ]
   },
   {
    "id": "bounce",
    "label": "Bounce",
    "value": 0.35,
    "bindings": [
     {
      "node": "ground",
      "parameter": "restitution"
     }
    ]
   }
  ]
 },
 {
  "id": "rain-splash",
  "label": "Rain with splashes",
  "description": "Falling droplets that die on the ground and spawn splash bursts.",
  "durationTicks": 240,
  "anchors": [],
  "nodes": [
   {
    "id": "sched",
    "type": "Schedule",
    "params": {
     "startTicks": 0,
     "durationTicks": 200,
     "mode": "window"
    }
   },
   {
    "id": "clouds",
    "type": "Emitter",
    "params": {
     "shape": "box",
     "direction": [
      0,
      -1,
      0
     ],
     "radius": 1.6,
     "rate": 90,
     "burst": 0,
     "speedMin": 6,
     "speedMax": 7.5,
     "lifetimeMin": 2,
     "lifetimeMax": 2
    }
   },
   {
    "id": "dropsize",
    "type": "InitialProperties",
    "params": {
     "sizeMin": 0.025,
     "sizeMax": 0.035,
     "rotationMin": 0,
     "rotationMax": 0,
     "angularVelocityMin": 0,
     "angularVelocityMax": 0
    }
   },
   {
    "id": "grav",
    "type": "Gravity"
   },
   {
    "id": "ground",
    "type": "GroundCollision",
    "params": {
     "mode": "kill"
    }
   },
   {
    "id": "dropmat",
    "type": "Material",
    "params": {
     "template": "SpriteTextured",
     "sprite": "droplet",
     "blend": "normal",
     "opacity": 1,
     "emission": 1.5
    }
   },
   {
    "id": "drops",
    "type": "BillboardRenderer",
    "params": {
     "alignment": "velocity",
     "stretchRatio": 6,
     "pivot": 0.8
    }
   },
   {
    "id": "splash",
    "type": "Emitter",
    "params": {
     "shape": "cone",
     "direction": [
      0,
      1,
      0
     ],
     "coneAngle": 0.9,
     "radius": 0.03,
     "burst": 7,
     "rate": 0,
     "speedMin": 1,
     "speedMax": 2.4,
     "lifetimeMin": 0.3,
     "lifetimeMax": 0.55,
     "useEventPosition": true
    }
   },
   {
    "id": "splashsize",
    "type": "InitialProperties",
    "params": {
     "sizeMin": 0.04,
     "sizeMax": 0.07,
     "rotationMin": 0,
     "rotationMax": 0,
     "angularVelocityMin": 0,
     "angularVelocityMax": 0
    }
   },
   {
    "id": "splashgrav",
    "type": "Gravity"
   },
   {
    "id": "splashground",
    "type": "GroundCollision",
    "params": {
     "mode": "kill"
    }
   },
   {
    "id": "splashmat",
    "type": "Material",
    "params": {
     "template": "SpriteTextured",
     "sprite": "soft-glow",
     "blend": "additive",
     "tint": {
      "srgb": "#CFEFFF",
      "alpha": 1
     },
     "emission": 1
    }
   },
   {
    "id": "splashes",
    "type": "BillboardRenderer",
    "params": {
     "alignment": "velocity",
     "stretchRatio": 2,
     "opacityOverLife": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 1
       },
       {
        "x": 1,
        "y": 0
       }
      ]
     }
    }
   }
  ],
  "edges": [
   [
    "node-source.out",
    "clouds.anchor"
   ],
   [
    "sched.window",
    "clouds.window"
   ],
   [
    "clouds.particles",
    "dropsize.particles"
   ],
   [
    "dropsize.particles",
    "grav.particles"
   ],
   [
    "grav.particles",
    "ground.particles"
   ],
   [
    "ground.particles",
    "drops.particles"
   ],
   [
    "dropmat.material",
    "drops.material"
   ],
   [
    "ground.collision",
    "splash.trigger"
   ],
   [
    "splash.particles",
    "splashsize.particles"
   ],
   [
    "splashsize.particles",
    "splashgrav.particles"
   ],
   [
    "splashgrav.particles",
    "splashground.particles"
   ],
   [
    "splashground.particles",
    "splashes.particles"
   ],
   [
    "splashmat.material",
    "splashes.material"
   ],
   [
    "drops.visual",
    "node-output.visual"
   ],
   [
    "splashes.visual",
    "node-output.visual"
   ]
  ],
  "knobs": [
   {
    "id": "rain",
    "label": "Rain rate",
    "value": 90,
    "bindings": [
     {
      "node": "clouds",
      "parameter": "rate"
     }
    ]
   },
   {
    "id": "area",
    "label": "Rain area",
    "value": 1.6,
    "bindings": [
     {
      "node": "clouds",
      "parameter": "radius"
     }
    ]
   },
   {
    "id": "splash",
    "label": "Splash drops",
    "value": 7,
    "bindings": [
     {
      "node": "splash",
      "parameter": "burst"
     }
    ]
   },
   {
    "id": "splash-speed",
    "label": "Splash speed",
    "value": 2.4,
    "bindings": [
     {
      "node": "splash",
      "parameter": "speedMax"
     },
     {
      "node": "splash",
      "parameter": "speedMin",
      "scale": 0.42
     }
    ]
   }
  ]
 },
 {
  "id": "impact-flash",
  "label": "Impact flash",
  "description": "Timed glow sprite with a spark burst at Target.",
  "durationTicks": 90,
  "anchors": [
   {
    "id": "groundpoint",
    "position": [
     0,
     0.02,
     0
    ]
   }
  ],
  "nodes": [
   {
    "id": "hit",
    "type": "Schedule",
    "params": {
     "startTicks": 10,
     "durationTicks": 30,
     "mode": "window"
    }
   },
   {
    "id": "glowmat",
    "type": "Material",
    "params": {
     "template": "SpriteTextured",
     "sprite": "soft-glow",
     "blend": "additive",
     "emission": 1,
     "variant": 1
    }
   },
   {
    "id": "flash",
    "type": "SpriteRenderer",
    "params": {
     "size": 2.2,
     "spin": 1.5,
     "sizeOverWindow": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 0.2
       },
       {
        "x": 0.15,
        "y": 1
       },
       {
        "x": 1,
        "y": 1.4
       }
      ]
     },
     "opacityOverWindow": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 1
       },
       {
        "x": 1,
        "y": 0
       }
      ]
     },
     "colorOverWindow": {
      "stops": [
       {
        "position": 0,
        "color": {
         "srgb": "#FFFFFF",
         "alpha": 1
        }
       },
       {
        "position": 0.4,
        "color": {
         "srgb": "#FFB060",
         "alpha": 1
        }
       },
       {
        "position": 1,
        "color": {
         "srgb": "#FF3010",
         "alpha": 1
        }
       }
      ]
     }
    }
   },
   {
    "id": "sparks",
    "type": "Emitter",
    "params": {
     "shape": "sphere",
     "radius": 0.05,
     "burst": 80,
     "rate": 0,
     "speedMin": 2,
     "speedMax": 6,
     "lifetimeMin": 0.4,
     "lifetimeMax": 0.9
    }
   },
   {
    "id": "ip",
    "type": "InitialProperties",
    "params": {
     "sizeMin": 0.02,
     "sizeMax": 0.04,
     "rotationMin": 0,
     "rotationMax": 0,
     "angularVelocityMin": 0,
     "angularVelocityMax": 0
    }
   },
   {
    "id": "grav",
    "type": "Gravity"
   },
   {
    "id": "sparkmat",
    "type": "Material",
    "params": {
     "template": "SpriteTextured",
     "sprite": "spark-streak",
     "blend": "additive",
     "tint": {
      "srgb": "#FFD080",
      "alpha": 1
     }
    }
   },
   {
    "id": "bb",
    "type": "BillboardRenderer",
    "params": {
     "alignment": "velocity",
     "stretchRatio": 5,
     "pivot": 0.8
    }
   },
   {
    "id": "ground",
    "type": "Anchor",
    "params": {
     "anchorId": "groundpoint"
    }
   },
   {
    "id": "ringmat",
    "type": "Material",
    "params": {
     "template": "SpriteTextured",
     "sprite": "ripple-ring",
     "variant": 0,
     "blend": "additive",
     "tint": {
      "srgb": "#FFB060",
      "alpha": 1
     },
     "emission": 0.5
    }
   },
   {
    "id": "shockwave",
    "type": "SpriteRenderer",
    "params": {
     "size": 1,
     "alignment": "worldAxis",
     "sizeOverWindow": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 0.2
       },
       {
        "x": 1,
        "y": 5
       }
      ]
     },
     "opacityOverWindow": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 1
       },
       {
        "x": 1,
        "y": 0
       }
      ]
     }
    }
   }
  ],
  "edges": [
   [
    "node-target.out",
    "flash.anchor"
   ],
   [
    "glowmat.material",
    "flash.material"
   ],
   [
    "hit.window",
    "flash.window"
   ],
   [
    "node-target.out",
    "sparks.anchor"
   ],
   [
    "hit.start",
    "sparks.trigger"
   ],
   [
    "sparks.particles",
    "ip.particles"
   ],
   [
    "ip.particles",
    "grav.particles"
   ],
   [
    "grav.particles",
    "bb.particles"
   ],
   [
    "sparkmat.material",
    "bb.material"
   ],
   [
    "flash.visual",
    "node-output.visual"
   ],
   [
    "bb.visual",
    "node-output.visual"
   ],
   [
    "ground.out",
    "shockwave.anchor"
   ],
   [
    "ringmat.material",
    "shockwave.material"
   ],
   [
    "hit.window",
    "shockwave.window"
   ],
   [
    "shockwave.visual",
    "node-output.visual"
   ]
  ],
  "knobs": [
   {
    "id": "flash",
    "label": "Flash size",
    "value": 2.2,
    "bindings": [
     {
      "node": "flash",
      "parameter": "size"
     }
    ]
   },
   {
    "id": "sparks",
    "label": "Sparks",
    "value": 80,
    "bindings": [
     {
      "node": "sparks",
      "parameter": "burst"
     }
    ]
   },
   {
    "id": "speed",
    "label": "Spark speed",
    "value": 6,
    "bindings": [
     {
      "node": "sparks",
      "parameter": "speedMax"
     },
     {
      "node": "sparks",
      "parameter": "speedMin",
      "scale": 0.33
     }
    ]
   }
  ]
 },
 {
  "id": "arc-beam",
  "label": "Arc beam",
  "description": "Textured electric arc Source→Target on a jagged, re-rolling path with a soft glow ribbon.",
  "durationTicks": 90,
  "anchors": [],
  "nodes": [
   {
    "id": "line",
    "type": "LinePath",
    "params": {
     "samples": 48
    }
   },
   {
    "id": "jag",
    "type": "JaggedPath",
    "params": {
     "amplitude": 0.18,
     "regenerationHz": 20,
     "samples": 48
    }
   },
   {
    "id": "on",
    "type": "Schedule",
    "params": {
     "startTicks": 5,
     "durationTicks": 70,
     "mode": "window"
    }
   },
   {
    "id": "arcmat",
    "type": "Material",
    "params": {
     "template": "SpriteTextured",
     "sprite": "electric-arc",
     "blend": "additive",
     "tint": {
      "srgb": "#B8E2FF",
      "alpha": 1
     },
     "emission": 1.5
    }
   },
   {
    "id": "core",
    "type": "RibbonRenderer",
    "params": {
     "width": 0.6,
     "endFade": 0.08
    }
   },
   {
    "id": "glowmat",
    "type": "Material",
    "params": {
     "blend": "additive",
     "tint": {
      "srgb": "#3A7BFF",
      "alpha": 1
     },
     "opacity": 0.35
    }
   },
   {
    "id": "halo",
    "type": "RibbonRenderer",
    "params": {
     "width": 0.35,
     "endFade": 0.1
    }
   }
  ],
  "edges": [
   [
    "node-source.out",
    "line.start"
   ],
   [
    "node-target.out",
    "line.end"
   ],
   [
    "line.paths",
    "jag.paths"
   ],
   [
    "jag.paths",
    "core.paths"
   ],
   [
    "line.paths",
    "halo.paths"
   ],
   [
    "arcmat.material",
    "core.material"
   ],
   [
    "glowmat.material",
    "halo.material"
   ],
   [
    "on.window",
    "core.window"
   ],
   [
    "on.window",
    "halo.window"
   ],
   [
    "halo.visual",
    "node-output.visual"
   ],
   [
    "core.visual",
    "node-output.visual"
   ]
  ],
  "knobs": [
   {
    "id": "width",
    "label": "Beam width",
    "value": 0.6,
    "bindings": [
     {
      "node": "core",
      "parameter": "width"
     }
    ]
   },
   {
    "id": "jagged",
    "label": "Jaggedness",
    "value": 0.18,
    "bindings": [
     {
      "node": "jag",
      "parameter": "amplitude"
     }
    ]
   },
   {
    "id": "flicker",
    "label": "Re-roll rate",
    "value": 20,
    "bindings": [
     {
      "node": "jag",
      "parameter": "regenerationHz"
     }
    ]
   },
   {
    "id": "glow",
    "label": "Glow width",
    "value": 0.35,
    "bindings": [
     {
      "node": "halo",
      "parameter": "width"
     }
    ]
   }
  ]
 },
 {
  "id": "fireball",
  "label": "Fireball",
  "description": "Projectile along an arc: glowing core, flame trail, moving light, impact sparks, flash and light.",
  "durationTicks": 120,
  "anchors": [],
  "nodes": [
   {
    "id": "arc",
    "type": "BezierPath",
    "params": {
     "startHandle": [
      1.5,
      1.6,
      0
     ],
     "endHandle": [
      -1,
      1.2,
      0
     ],
     "samples": 48
    }
   },
   {
    "id": "flight",
    "type": "Schedule",
    "params": {
     "startTicks": 0,
     "durationTicks": 42,
     "mode": "window"
    }
   },
   {
    "id": "ball",
    "type": "PathFollower",
    "params": {
     "durationTicks": 40,
     "easing": "easeIn"
    }
   },
   {
    "id": "coremat",
    "type": "Material",
    "params": {
     "template": "SpriteTextured",
     "sprite": "soft-glow",
     "variant": 1,
     "blend": "additive",
     "tint": {
      "srgb": "#FFC070",
      "alpha": 1
     },
     "emission": 1.5
    }
   },
   {
    "id": "core",
    "type": "SpriteRenderer",
    "params": {
     "size": 1.4,
     "spin": 6
    }
   },
   {
    "id": "trailem",
    "type": "Emitter",
    "params": {
     "shape": "sphere",
     "radius": 0.12,
     "rate": 900,
     "burst": 0,
     "speedMin": 0.2,
     "speedMax": 0.8,
     "lifetimeMin": 0.35,
     "lifetimeMax": 0.7
    }
   },
   {
    "id": "trailip",
    "type": "InitialProperties",
    "params": {
     "sizeMin": 0.3,
     "sizeMax": 0.5,
     "rotationMin": -3,
     "rotationMax": 3,
     "angularVelocityMin": -2,
     "angularVelocityMax": 2
    }
   },
   {
    "id": "lift",
    "type": "Gravity",
    "params": {
     "acceleration": [
      0,
      1.5,
      0
     ]
    }
   },
   {
    "id": "turb",
    "type": "NoiseForce",
    "params": {
     "amplitude": 3,
     "frequency": 1.2,
     "evolution": 1.5
    }
   },
   {
    "id": "flamemat",
    "type": "Material",
    "params": {
     "template": "SpriteTextured",
     "sprite": "flame-tongue-b",
     "blend": "normal",
     "opacity": 0.6
    }
   },
   {
    "id": "flames",
    "type": "BillboardRenderer",
    "params": {
     "flipbookMode": "overLife",
     "sizeOverLife": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 0.8
       },
       {
        "x": 0.4,
        "y": 1.4
       },
       {
        "x": 1,
        "y": 0.6
       }
      ]
     },
     "opacityOverLife": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 1
       },
       {
        "x": 1,
        "y": 0
       }
      ]
     },
     "colorOverLife": {
      "stops": [
       {
        "position": 0,
        "color": {
         "srgb": "#FFFFFF",
         "alpha": 1
        }
       },
       {
        "position": 0.5,
        "color": {
         "srgb": "#FFB070",
         "alpha": 1
        }
       },
       {
        "position": 1,
        "color": {
         "srgb": "#602010",
         "alpha": 1
        }
       }
      ]
     }
    }
   },
   {
    "id": "balllight",
    "type": "PointLight",
    "params": {
     "color": {
      "srgb": "#FF9040",
      "alpha": 1
     },
     "intensity": 30,
     "range": 5,
     "flicker": 0.3,
     "intensityOverWindow": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 0.6
       },
       {
        "x": 1,
        "y": 1
       }
      ]
     }
    }
   },
   {
    "id": "boom",
    "type": "Emitter",
    "params": {
     "shape": "sphere",
     "radius": 0.1,
     "burst": 120,
     "rate": 0,
     "speedMin": 2,
     "speedMax": 7,
     "lifetimeMin": 0.4,
     "lifetimeMax": 1,
     "useEventPosition": true
    }
   },
   {
    "id": "boomip",
    "type": "InitialProperties",
    "params": {
     "sizeMin": 0.02,
     "sizeMax": 0.04,
     "rotationMin": 0,
     "rotationMax": 0,
     "angularVelocityMin": 0,
     "angularVelocityMax": 0
    }
   },
   {
    "id": "boomgrav",
    "type": "Gravity"
   },
   {
    "id": "boomdrag",
    "type": "Drag",
    "params": {
     "coefficient": 1.2
    }
   },
   {
    "id": "boomground",
    "type": "GroundCollision",
    "params": {
     "mode": "bounce",
     "restitution": 0.3,
     "friction": 0.5
    }
   },
   {
    "id": "sparkmat",
    "type": "Material",
    "params": {
     "template": "SpriteTextured",
     "sprite": "spark-streak",
     "blend": "additive"
    }
   },
   {
    "id": "sparks",
    "type": "BillboardRenderer",
    "params": {
     "alignment": "velocity",
     "stretchRatio": 5,
     "pivot": 0.8,
     "colorOverLife": {
      "stops": [
       {
        "position": 0,
        "color": {
         "srgb": "#FFFFFF",
         "alpha": 1
        }
       },
       {
        "position": 0.5,
        "color": {
         "srgb": "#FFA040",
         "alpha": 1
        }
       },
       {
        "position": 1,
        "color": {
         "srgb": "#A02000",
         "alpha": 0
        }
       }
      ]
     }
    }
   },
   {
    "id": "impactwin",
    "type": "Schedule",
    "params": {
     "startTicks": 40,
     "durationTicks": 30,
     "mode": "window"
    }
   },
   {
    "id": "flash",
    "type": "SpriteRenderer",
    "params": {
     "size": 3,
     "sizeOverWindow": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 0.3
       },
       {
        "x": 0.2,
        "y": 1
       },
       {
        "x": 1,
        "y": 1.3
       }
      ]
     },
     "opacityOverWindow": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 1
       },
       {
        "x": 1,
        "y": 0
       }
      ]
     },
     "colorOverWindow": {
      "stops": [
       {
        "position": 0,
        "color": {
         "srgb": "#FFFFFF",
         "alpha": 1
        }
       },
       {
        "position": 0.3,
        "color": {
         "srgb": "#FFA050",
         "alpha": 1
        }
       },
       {
        "position": 1,
        "color": {
         "srgb": "#FF3010",
         "alpha": 1
        }
       }
      ]
     }
    }
   },
   {
    "id": "impactlight",
    "type": "PointLight",
    "params": {
     "color": {
      "srgb": "#FFA050",
      "alpha": 1
     },
     "intensity": 80,
     "range": 7,
     "intensityOverWindow": {
      "domain": "normalized",
      "interpolation": "linear",
      "keys": [
       {
        "x": 0,
        "y": 1
       },
       {
        "x": 1,
        "y": 0
       }
      ]
     }
    }
   }
  ],
  "edges": [
   [
    "node-source.out",
    "arc.start"
   ],
   [
    "node-target.out",
    "arc.end"
   ],
   [
    "arc.paths",
    "ball.paths"
   ],
   [
    "flight.window",
    "ball.window"
   ],
   [
    "ball.anchor",
    "core.anchor"
   ],
   [
    "coremat.material",
    "core.material"
   ],
   [
    "flight.window",
    "core.window"
   ],
   [
    "ball.anchor",
    "trailem.anchor"
   ],
   [
    "flight.window",
    "trailem.window"
   ],
   [
    "trailem.particles",
    "trailip.particles"
   ],
   [
    "trailip.particles",
    "lift.particles"
   ],
   [
    "lift.particles",
    "turb.particles"
   ],
   [
    "turb.particles",
    "flames.particles"
   ],
   [
    "flamemat.material",
    "flames.material"
   ],
   [
    "ball.anchor",
    "balllight.anchor"
   ],
   [
    "flight.window",
    "balllight.window"
   ],
   [
    "ball.arrival",
    "boom.trigger"
   ],
   [
    "boom.particles",
    "boomip.particles"
   ],
   [
    "boomip.particles",
    "boomgrav.particles"
   ],
   [
    "boomgrav.particles",
    "boomdrag.particles"
   ],
   [
    "boomdrag.particles",
    "boomground.particles"
   ],
   [
    "boomground.particles",
    "sparks.particles"
   ],
   [
    "sparkmat.material",
    "sparks.material"
   ],
   [
    "node-target.out",
    "flash.anchor"
   ],
   [
    "coremat.material",
    "flash.material"
   ],
   [
    "impactwin.window",
    "flash.window"
   ],
   [
    "node-target.out",
    "impactlight.anchor"
   ],
   [
    "impactwin.window",
    "impactlight.window"
   ],
   [
    "flames.visual",
    "node-output.visual"
   ],
   [
    "core.visual",
    "node-output.visual"
   ],
   [
    "sparks.visual",
    "node-output.visual"
   ],
   [
    "flash.visual",
    "node-output.visual"
   ],
   [
    "balllight.visual",
    "node-output.visual"
   ],
   [
    "impactlight.visual",
    "node-output.visual"
   ]
  ],
  "knobs": [
   {
    "id": "travel",
    "label": "Travel ticks",
    "value": 40,
    "bindings": [
     {
      "node": "ball",
      "parameter": "durationTicks"
     }
    ]
   },
   {
    "id": "trail",
    "label": "Trail density",
    "value": 900,
    "bindings": [
     {
      "node": "trailem",
      "parameter": "rate"
     }
    ]
   },
   {
    "id": "core",
    "label": "Core size",
    "value": 1.4,
    "bindings": [
     {
      "node": "core",
      "parameter": "size"
     }
    ]
   },
   {
    "id": "impact",
    "label": "Impact sparks",
    "value": 120,
    "bindings": [
     {
      "node": "boom",
      "parameter": "burst"
     }
    ]
   },
   {
    "id": "flash",
    "label": "Flash size",
    "value": 3,
    "bindings": [
     {
      "node": "flash",
      "parameter": "size"
     }
    ]
   },
   {
    "id": "light",
    "label": "Ball light",
    "value": 30,
    "bindings": [
     {
      "node": "balllight",
      "parameter": "intensity"
     }
    ]
   }
  ]
 }
];
