// GENERATED by tools/bake-sprites.mjs — do not edit. Typed copy of assets/sprites/manifest.json.
import type { SpriteSheet } from './spriteLibrary.ts';

export const BUILTIN_SPRITES: readonly SpriteSheet[] = [
  { id: "flame-tongue-a", file: "flame-tongue-a.png", kind: "flipbook", cell: [256,256], columns: 4, rows: 4, blend: "normal" },
  { id: "flame-tongue-b", file: "flame-tongue-b.png", kind: "flipbook", cell: [256,256], columns: 4, rows: 4, blend: "normal" },
  { id: "fire-puff", file: "fire-puff.png", kind: "flipbook", cell: [256,256], columns: 4, rows: 4, blend: "normal" },
  { id: "smoke-puff", file: "smoke-puff.png", kind: "flipbook", cell: [256,256], columns: 4, rows: 4, blend: "normal" },
  { id: "foam", file: "foam.png", kind: "flipbook", cell: [256,256], columns: 4, rows: 4, blend: "normal" },
  { id: "soft-glow", file: "soft-glow.png", kind: "variants", cell: [256,256], columns: 2, rows: 2, blend: "additive" },
  { id: "spark-streak", file: "spark-streak.png", kind: "variants", cell: [256,256], columns: 2, rows: 2, blend: "additive" },
  { id: "electric-arc", file: "electric-arc.png", kind: "variants", cell: [256,256], columns: 2, rows: 2, blend: "additive" },
  { id: "droplet", file: "droplet.png", kind: "variants", cell: [256,256], columns: 2, rows: 2, blend: "normal" },
  { id: "bubble", file: "bubble.png", kind: "variants", cell: [256,256], columns: 2, rows: 2, blend: "normal" },
  { id: "ripple-ring", file: "ripple-ring.png", kind: "variants", cell: [256,256], columns: 2, rows: 2, blend: "normal" },
  { id: "dissolve-noise", file: "dissolve-noise.png", kind: "texture", cell: [256,256], columns: 1, rows: 1, blend: "n/a" },
];
